// Org resolution without a session (PLAN Task 0.4).
//
// The payment webhooks are mounted *before* `authMiddleware` on purpose, so they
// have no `c.get("organizationId")` to read. They resolve the tenant from the
// `payments` row written at checkout instead. Three properties are asserted here,
// all of them named in the Phase 0 definition of done:
//
//   1. Credits land on the organization the `payments` row names, even when the
//      provider metadata names a user who now belongs to a different one. Stripe
//      and Coinbase retry for up to three days, and D3 lets a user move tenant
//      inside that window — re-deriving the org from their current membership
//      would credit their firm's purchase to somebody else's wallet.
//   2. Redelivery of the same event is a no-op.
//   3. An event with no matching `payments` row produces a **5xx**, so the
//      provider retries. A 200 there would drop a paid purchase silently.
//
// Both webhook secrets must be in the environment before `config/env.ts` parses
// it, which happens the moment anything imports the app — hence the dynamic
// imports below, the same shape `lib/billing/spend.test.ts` uses.

import { createHmac, randomUUID } from "node:crypto";
import { describe, expect, it, vi } from "vitest";

process.env.STRIPE_SECRET_KEY = "sk_test_webhook_org_resolution";
process.env.STRIPE_WEBHOOK_SECRET = "whsec_test_webhook_org_resolution";
process.env.COINBASE_COMMERCE_API_KEY = "cb_test_webhook_org_resolution";
process.env.COINBASE_COMMERCE_WEBHOOK_SECRET = "cb_whsec_test_webhook_org_resolution";

const { default: app } = await import("../../app.js");
const { db } = await import("../../db/index.js");
const { creditLedger, creditPackages, payments, walletBalance } = await import(
  "../../db/schema.js"
);
const { seedOrg, seedUser } = await import("../../test/factories.js");
const { getStripe } = await import("../billing/stripe.js");
const { eq } = await import("drizzle-orm");

const ORIGIN = "http://api.test";
const PACKAGE_CREDITS = 250;

// ==================== fixtures ====================

/**
 * The case D3 creates: a purchase made while the buyer was in `payingOrg`, and a
 * webhook that arrives after they have moved to `currentOrg`. The provider
 * metadata still names the buyer, so anything that trusts it credits the wrong
 * tenant.
 */
async function seedMovedBuyerPurchase(externalId: string) {
  const payingOrg = await seedOrg({ name: "The firm that paid" });
  const currentOrg = await seedOrg({ name: "The firm they moved to" });
  const buyer = await seedUser({ organizationId: currentOrg.id });

  const packageId = `pkg-${randomUUID()}`;
  await db.insert(creditPackages).values({
    id: packageId,
    credits: PACKAGE_CREDITS,
    priceMinor: 4900,
    currency: "usd",
    rail: "stripe",
  });

  const paymentId = randomUUID();
  await db.insert(payments).values({
    id: paymentId,
    userId: buyer.id,
    organizationId: payingOrg.id,
    packageId,
    rail: "stripe",
    externalId,
    status: "pending",
    amountMinor: 4900,
    currency: "usd",
    creditsPurchased: PACKAGE_CREDITS,
  });

  return { payingOrg, currentOrg, buyer, packageId, paymentId };
}

/** A buyer and a package with no `payments` row behind them. */
async function seedUnrecordedPurchase() {
  const org = await seedOrg({ name: "No payments row" });
  const buyer = await seedUser({ organizationId: org.id });
  const packageId = `pkg-${randomUUID()}`;
  await db.insert(creditPackages).values({
    id: packageId,
    credits: PACKAGE_CREDITS,
    priceMinor: 4900,
    currency: "usd",
    rail: "stripe",
  });
  return { org, buyer, packageId };
}

// ==================== transports ====================

async function post(
  path: string,
  body: string,
  headers: Record<string, string>
): Promise<Response> {
  return app.fetch(
    new Request(new URL(path, ORIGIN), {
      method: "POST",
      headers: { "Content-Type": "application/json", ...headers },
      body,
    })
  );
}

// Real signatures, generated by the same library that verifies them, so
// `constructEvent` stays on its production code path.
function stripeWebhook(event: unknown): Promise<Response> {
  const body = JSON.stringify(event);
  const stripe = getStripe();
  if (!stripe) throw new Error("Stripe is not configured for this test run");
  const signature = stripe.webhooks.generateTestHeaderString({
    payload: body,
    secret: process.env.STRIPE_WEBHOOK_SECRET as string,
  });
  return post("/api/billing/webhooks/stripe", body, { "stripe-signature": signature });
}

function coinbaseWebhook(envelope: unknown): Promise<Response> {
  const body = JSON.stringify(envelope);
  const signature = createHmac("sha256", process.env.COINBASE_COMMERCE_WEBHOOK_SECRET as string)
    .update(body)
    .digest("hex");
  return post("/api/billing/webhooks/coinbase", body, { "x-cc-webhook-signature": signature });
}

function checkoutSessionCompleted(opts: {
  sessionId: string;
  userId: string;
  packageId: string;
}): unknown {
  return {
    id: `evt_${randomUUID()}`,
    object: "event",
    type: "checkout.session.completed",
    created: Math.floor(Date.now() / 1000),
    data: {
      object: {
        id: opts.sessionId,
        object: "checkout.session",
        payment_status: "paid",
        metadata: { userId: opts.userId, packageId: opts.packageId },
      },
    },
  };
}

function chargeConfirmed(opts: {
  chargeId: string;
  userId: string;
  packageId: string;
}): unknown {
  return {
    attempt_number: 1,
    event: {
      id: `evt_${randomUUID()}`,
      type: "charge:confirmed",
      api_version: "2018-03-22",
      created_at: new Date().toISOString(),
      data: {
        id: opts.chargeId,
        code: "TESTCODE",
        hosted_url: "https://commerce.coinbase.com/charges/TESTCODE",
        metadata: { userId: opts.userId, packageId: opts.packageId },
      },
    },
  };
}

// ==================== assertions ====================

async function walletCredits(organizationId: string): Promise<number | null> {
  const row = await db.query.walletBalance.findFirst({
    where: eq(walletBalance.organizationId, organizationId),
  });
  return row?.credits ?? null;
}

async function ledgerFor(organizationId: string) {
  return db.query.creditLedger.findMany({
    where: eq(creditLedger.organizationId, organizationId),
  });
}

// The two "no payments row" cases log before returning 500. Silencing keeps the
// deliberate failure from reading like a broken test.
async function expectingLoggedError<T>(run: () => Promise<T>): Promise<T> {
  const silenced = vi.spyOn(console, "error").mockImplementation(() => {});
  try {
    return await run();
  } finally {
    silenced.mockRestore();
  }
}

// ==================== Stripe ====================

describe("Stripe webhook — organization resolution", () => {
  it("credits the organization named by the payments row, not the buyer's current one", async () => {
    const sessionId = `cs_test_${randomUUID()}`;
    const { payingOrg, currentOrg, buyer, packageId } = await seedMovedBuyerPurchase(sessionId);

    const res = await stripeWebhook(
      checkoutSessionCompleted({ sessionId, userId: buyer.id, packageId })
    );

    expect(res.status).toBe(200);
    expect(await walletCredits(payingOrg.id)).toBe(PACKAGE_CREDITS);
    // Nothing at all should exist for the tenant the buyer moved to.
    expect(await walletCredits(currentOrg.id)).toBeNull();

    const rows = await ledgerFor(payingOrg.id);
    expect(rows).toHaveLength(1);
    expect(rows[0]).toMatchObject({
      delta: PACKAGE_CREDITS,
      reason: "purchase",
      // The ledger keeps the per-user attribution even though the wallet is the
      // paying organization's.
      userId: buyer.id,
      idempotencyKey: `purchase:${sessionId}`,
    });
    expect(await ledgerFor(currentOrg.id)).toEqual([]);
  });

  it("marks the payments row succeeded", async () => {
    const sessionId = `cs_test_${randomUUID()}`;
    const { buyer, packageId, paymentId } = await seedMovedBuyerPurchase(sessionId);

    await stripeWebhook(checkoutSessionCompleted({ sessionId, userId: buyer.id, packageId }));

    const row = await db.query.payments.findFirst({ where: eq(payments.id, paymentId) });
    expect(row?.status).toBe("succeeded");
  });

  it("is a no-op on redelivery", async () => {
    const sessionId = `cs_test_${randomUUID()}`;
    const { payingOrg, buyer, packageId } = await seedMovedBuyerPurchase(sessionId);
    const event = checkoutSessionCompleted({ sessionId, userId: buyer.id, packageId });

    const first = await stripeWebhook(event);
    const second = await stripeWebhook(event);

    expect([first.status, second.status]).toEqual([200, 200]);
    expect(await walletCredits(payingOrg.id)).toBe(PACKAGE_CREDITS);
    expect(await ledgerFor(payingOrg.id)).toHaveLength(1);
  });

  it("returns 5xx when no payments row resolves the organization, so Stripe retries", async () => {
    const { org, buyer, packageId } = await seedUnrecordedPurchase();
    const sessionId = `cs_test_${randomUUID()}`;

    const res = await expectingLoggedError(() =>
      stripeWebhook(checkoutSessionCompleted({ sessionId, userId: buyer.id, packageId }))
    );

    // A 200 here would be the worst outcome available: the provider stops
    // retrying and the customer has paid for credits nobody ever granted.
    expect(res.status).toBe(500);
    expect(await walletCredits(org.id)).toBeNull();
    expect(await ledgerFor(org.id)).toEqual([]);
  });

  it("rejects an unsigned request before any of this", async () => {
    const sessionId = `cs_test_${randomUUID()}`;
    const { payingOrg, buyer, packageId } = await seedMovedBuyerPurchase(sessionId);

    const res = await post(
      "/api/billing/webhooks/stripe",
      JSON.stringify(checkoutSessionCompleted({ sessionId, userId: buyer.id, packageId })),
      {}
    );

    expect(res.status).toBe(400);
    expect(await walletCredits(payingOrg.id)).toBeNull();
  });
});

// ==================== Coinbase Commerce ====================

describe("Coinbase webhook — organization resolution", () => {
  it("credits the organization named by the payments row, not the buyer's current one", async () => {
    const chargeId = `charge_${randomUUID()}`;
    const { payingOrg, currentOrg, buyer, packageId } = await seedMovedBuyerPurchase(chargeId);

    const res = await coinbaseWebhook(chargeConfirmed({ chargeId, userId: buyer.id, packageId }));

    expect(res.status).toBe(200);
    expect(await walletCredits(payingOrg.id)).toBe(PACKAGE_CREDITS);
    expect(await walletCredits(currentOrg.id)).toBeNull();
    expect(await ledgerFor(payingOrg.id)).toHaveLength(1);
  });

  it("is a no-op on redelivery", async () => {
    const chargeId = `charge_${randomUUID()}`;
    const { payingOrg, buyer, packageId } = await seedMovedBuyerPurchase(chargeId);
    const envelope = chargeConfirmed({ chargeId, userId: buyer.id, packageId });

    const first = await coinbaseWebhook(envelope);
    const second = await coinbaseWebhook(envelope);

    expect([first.status, second.status]).toEqual([200, 200]);
    expect(await walletCredits(payingOrg.id)).toBe(PACKAGE_CREDITS);
    expect(await ledgerFor(payingOrg.id)).toHaveLength(1);
  });

  it("returns 5xx when no payments row resolves the organization, so Coinbase retries", async () => {
    const { org, buyer, packageId } = await seedUnrecordedPurchase();
    const chargeId = `charge_${randomUUID()}`;

    const res = await expectingLoggedError(() =>
      coinbaseWebhook(chargeConfirmed({ chargeId, userId: buyer.id, packageId }))
    );

    expect(res.status).toBe(500);
    expect(await walletCredits(org.id)).toBeNull();
    expect(await ledgerFor(org.id)).toEqual([]);
  });
});
